services:

  web:
    build: .docker
    tty: true
    ports:
      - 5000:5000
    volumes:
      - .:/workspace
    working_dir: /workspace/web

  firebase:
    build: .docker
    tty: true
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8080:8080 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
    volumes:
      - .:/workspace
    working_dir: /workspace
